#!/usr/bin/python2
from sneakers import Exfil
from sneakers import util


def test_file_b64():
    mod = "file"

    enc = ["b64"]

    dataz = "very secret and private message"

    t = Exfil(mod, enc)
    t.set_channel_params({'sending': {'filename': 'test.txt'}})
    t.set_channel_params({'receiving': {'filename': 'test.txt'}})
    t.set_encoder_params(enc[0], {})

    print t.channel_config()
    print t.encoder_config(enc[0])

    t.send(dataz)

    print t.receive()


def test_github():
    channel = "githubc"
    enc = []

    content = "secret message test"

    t = Exfil(channel, enc)

    ret = t.send(content)

    print ret

    t.set_opt_channel_params({'receiving': {'id': ret}})

    print t.receive()


encoders = util.list_encoders(verbose=True)
for encoder in encoders:
    print "Encoder name: {0}".format(encoder['encoder'])
    print "Info: {0}".format(encoder['info'])
    print "="*20

test_github()
